name: Build and Release WinForms .NET 4.8 App

on:
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build:
    name: Build WinForms .NET 4.8 App
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Framework
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build the project
        run: msbuild ./SitefinityHelper.sln /p:Configuration=Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ./Sitefinity_Helper/bin/Release

  release:
    name: Create and Upload Build to Release
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Upload exe to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./Sitefinity_Helper/bin/Release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
